# Generated by Django 2.1.5 on 2019-01-14 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('brochurename', models.CharField(blank=True, max_length=250)),
                ('picturename', models.CharField(blank=True, max_length=250)),
                ('modelyear', models.CharField(blank=True, max_length=4)),
                ('releasedate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
                ('wheelbase', models.CharField(blank=True, max_length=5)),
                ('ftrack', models.CharField(blank=True, max_length=4)),
                ('rtrack', models.CharField(blank=True, max_length=4)),
                ('length', models.CharField(blank=True, max_length=5)),
                ('width', models.CharField(blank=True, max_length=5)),
                ('height', models.CharField(blank=True, max_length=4)),
                ('clearance', models.CharField(blank=True, max_length=4)),
                ('marketlocation', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carbodytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbodytypes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carmaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('logo', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=1)),
                ('create_year', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmakers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('generation', models.CharField(blank=True, max_length=2)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('picturename', models.CharField(blank=True, max_length=250)),
                ('releaseyear', models.CharField(blank=True, max_length=4)),
                ('endyear', models.CharField(blank=True, max_length=4)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('carmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='cardb.Carmaker')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cartrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('drivetype', models.CharField(blank=True, max_length=10)),
                ('maxspeed', models.CharField(blank=True, max_length=5)),
                ('enginename', models.CharField(blank=True, max_length=20)),
                ('engine_modelno', models.CharField(blank=True, max_length=5)),
                ('enginecc', models.CharField(blank=True, max_length=5)),
                ('engine_maxpower', models.CharField(blank=True, max_length=4)),
                ('engine_maxnm', models.CharField(blank=True, max_length=4)),
                ('transmissionname', models.CharField(blank=True, max_length=10)),
                ('fueltype', models.CharField(blank=True, max_length=20)),
                ('wheelbase', models.CharField(blank=True, max_length=5)),
                ('ftrack', models.CharField(blank=True, max_length=4)),
                ('rtrack', models.CharField(blank=True, max_length=4)),
                ('length', models.CharField(blank=True, max_length=5)),
                ('width', models.CharField(blank=True, max_length=5)),
                ('height', models.CharField(blank=True, max_length=4)),
                ('clearance', models.CharField(blank=True, max_length=4)),
                ('gvw', models.CharField(blank=True, max_length=6)),
                ('curbweight', models.CharField(blank=True, max_length=6)),
                ('fweight', models.CharField(blank=True, max_length=6)),
                ('rweight', models.CharField(blank=True, max_length=6)),
                ('mpg', models.CharField(blank=True, max_length=4)),
                ('tire', models.CharField(blank=True, max_length=20)),
                ('wheel', models.CharField(blank=True, max_length=20)),
                ('turncircle', models.CharField(blank=True, max_length=5)),
                ('steerradio', models.CharField(blank=True, max_length=5)),
                ('esc', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartrims', to='cardb.Car')),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartrims', to='cardb.Carmodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartrims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('name_cn', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pttypes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartrim',
            name='pttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartrims', to='cardb.Pttype'),
        ),
        migrations.AddField(
            model_name='cartrim',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='carbodytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cardb.Carbodytype'),
        ),
        migrations.AddField(
            model_name='car',
            name='carmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cardb.Carmaker'),
        ),
        migrations.AddField(
            model_name='car',
            name='carmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cardb.Carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
