# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='ftrack',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='rtrack',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='wheelbase',
        ),
        migrations.AddField(
            model_name='car',
            name='bodytype',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='brochurename',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='car',
            name='curbweight',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetype',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='enginecc',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='enginecylcontrol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='engineinj',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='engineintake',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='engineliter',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='enginepercyl',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='enginestoke',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='enginetype',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='esc',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='ftrack',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='fueltype',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='gvw',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='h_rpm',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='height',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='hp',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='length',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='modelyear',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='car',
            name='mpg',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='nm',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='picturename',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='rtrack',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='t_npm',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='car',
            name='trans',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='wheelbase',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='car',
            name='width',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brochurename',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='marketlocation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='modelyear',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='picturename',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='platform',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='releasedate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='create_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='name_cn',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name_cn',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name_cn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
