# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardb', '0002_auto_20171010_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
