# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='auth_user',
        ),
    ]
